name: "🚫 Close Inactive"

on:
  # schedule:
  #   - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  close-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 30
          exclude-labels: "enhancement,bug"
          close-reason: "not_planned"
          body: |
            This issue was closed due to inactive more than 30 days. You can reopen it if you think it should continue.
